import { PermissionLevel } from "../config/permissions.js";
import { config } from "../config/settings.js";
const IMG = "https://files.catbox.moe/mio9it.jpg";
export default {
  name: "menuadmav", aliases: ["menuadminav","admavancado"],
  description: "Menu admin avançado", permission: PermissionLevel.USER,
  async execute({ sock, msg, jid, sender, senderNumber }) {
    const p = config.prefix;
    const txt = [
      `╭┈⊰ 🪷 『 *${config.botName}* 』`,
      `┊ 👤 ${senderNumber}`,
      `╰─┈┈┈┈┈◜❁◞┈┈┈┈┈─╯`,
      ``,
      `╭┈❁ *⚠️ ADVERTÊNCIAS*`,
      `┊`,
      `┊ 🪷 ${p}adv       — Advertir`,
      `┊ 🪷 ${p}inadv     — Remover adv`,
      `┊ 🪷 ${p}listadv   — Listar adv`,
      `┊ 🪷 ${p}limitewarn — Limite de adv`,
      `╰─┈┈┈┈┈◜❁◞┈┈┈┈┈─╯`,
      ``,
      `╭┈❁ *⏳ TEMPORÁRIOS*`,
      `┊`,
      `┊ 🪷 ${p}tempban   — Ban temporário`,
      `┊ 🪷 ${p}tempmute  — Mute temporário`,
      `┊ 🪷 ${p}ban2      — Ban contagem 10s`,
      `╰─┈┈┈┈┈◜❁◞┈┈┈┈┈─╯`,
      ``,
      `╭┈❁ *🎯 EVENTOS & DESAFIOS*`,
      `┊`,
      `┊ 🪷 ${p}desafio   — Desafio c/ tempo`,
      `┊ 🪷 ${p}premio    — Premiar membro`,
      `┊ 🪷 ${p}evento    — Agendar evento`,
      `┊ 🪷 ${p}alerta    — Agendar alerta`,
      `┊ 🪷 ${p}agenda    — Ver agendamentos`,
      `┊ 🪷 ${p}enquete   — Criar enquete/poll`,
      `╰─┈┈┈┈┈◜❁◞┈┈┈┈┈─╯`,
      ``,
      `╭┈❁ *📋 LOGS & DADOS*`,
      `┊`,
      `┊ 🪷 ${p}logban    — Log de bans`,
      `┊ 🪷 ${p}historico — Histórico user`,
      `┊ 🪷 ${p}resetuser — Resetar user`,
      `┊ 🪷 ${p}resumo    — Resumo do grupo`,
      `╰─┈┈┈┈┈◜❁◞┈┈┈┈┈─╯`,
      ``,
      `╭┈❁ *⚙️ PERSONALIZAÇÃO*`,
      `┊`,
      `┊ 🪷 ${p}addauto   — Auto-resposta`,
      `┊ 🪷 ${p}listauto  — Listar auto`,
      `┊ 🪷 ${p}delauto   — Remover auto`,
      `┊ 🪷 ${p}addnopref — Palavra proibida`,
      `┊ 🪷 ${p}addcmd    — Cmd personalizado`,
      `┊ 🪷 ${p}listcmd   — Listar cmds`,
      `┊ 🪷 ${p}regras    — Regras do grupo`,
      `┊ 🪷 ${p}addregra  — Adicionar regra`,
      `┊ 🪷 ${p}bemvindo  — Boas-vindas`,
      `╰─┈┈┈┈┈◜❁◞┈┈┈┈┈─╯`,
    ].join("\n");
    await sock.sendMessage(jid, { image: { url: IMG }, caption: txt, mentions: [sender] }, { quoted: msg });
  },
};
