import { PermissionLevel } from "../config/permissions.js";
import { config } from "../config/settings.js";
const IMG = "https://files.catbox.moe/mio9it.jpg";
export default {
  name: "menuadm", aliases: ["menuadmin","admenu"],
  description: "Menu admin", permission: PermissionLevel.USER,
  async execute({ sock, msg, jid, sender, senderNumber }) {
    const p = config.prefix;
    const txt = [
      `╭┈⊰ 🪷 『 *${config.botName}* 』`,
      `┊ 👤 ${senderNumber}`,
      `╰─┈┈┈┈┈◜❁◞┈┈┈┈┈─╯`,
      ``,
      `╭┈❁ *🛡️ GESTÃO DE USUÁRIOS*`,
      `┊`,
      `┊ 🪷 ${p}ban`,
      `┊ 🪷 ${p}promote  — Promover admin`,
      `┊ 🪷 ${p}demote   — Rebaixar admin`,
      `┊ 🪷 ${p}mute     — Mutar membro`,
      `┊ 🪷 ${p}unmute   — Desmutar`,
      `┊ 🪷 ${p}tempban  — Ban temporário`,
      `╰─┈┈┈┈┈◜❁◞┈┈┈┈┈─╯`,
      ``,
      `╭┈❁ *🔒 GRUPO*`,
      `┊`,
      `┊ 🪷 ${p}abrir    — Abrir grupo`,
      `┊ 🪷 ${p}fechar   — Fechar grupo`,
      `┊ 🪷 ${p}soadm    — Só admins`,
      `┊ 🪷 ${p}nomegrupo`,
      `┊ 🪷 ${p}descgrupo`,
      `┊ 🪷 ${p}fotogrupo`,
      `┊ 🪷 ${p}opengp   — Abrir gp`,
      `┊ 🪷 ${p}closegp  — Fechar gp`,
      `╰─┈┈┈┈┈◜❁◞┈┈┈┈┈─╯`,
      ``,
      `╭┈❁ *🔨 MODERAÇÃO*`,
      `┊`,
      `┊ 🪷 ${p}antilink — Anti-link`,
      `┊ 🪷 ${p}antilinksoft — Soft ban`,
      `┊ 🪷 ${p}antilinkhard — Hard ban`,
      `┊ 🪷 ${p}antiflood — Anti-flood`,
      `┊ 🪷 ${p}antiporn — Anti-18`,
      `┊ 🪷 ${p}mute2    — Mute silencioso (apaga msgs)`,
      `┊ 🪷 ${p}muteall  — Silenciar grupo`,
      `╰─┈┈┈┈┈◜❁◞┈┈┈┈┈─╯`,
      ``,
      `╭┈❁ *📢 MENSAGENS*`,
      `┊`,
      `┊ 🪷 ${p}hidetag  — Marcar todos`,
      `┊ 🪷 ${p}cita     — Marcar todos`,
      `┊ 🪷 ${p}marcar   — Marcar @`,
      `┊ 🪷 ${p}tagadmins — Só admins`,
      `┊ 🪷 ${p}times    — Sortear times`,
      `┊ 🪷 ${p}avisogrupo — Aviso oficial`,
      `╰─┈┈┈┈┈◜❁◞┈┈┈┈┈─╯`,
    ].join("\n");
    await sock.sendMessage(jid, { image: { url: IMG }, caption: txt, mentions: [sender] }, { quoted: msg });
  },
};
